server {
  listen 80 default_server;
  server_name test-wallet.loc;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://backend:3000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location = /index.html {
    add_header Cache-Control "no-store";
  }

  location = /flutter_service_worker.js {
    add_header Cache-Control "no-store";
  }

  location / {
    try_files $uri /index.html;
  }
}
